import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "./redux-provicer";
import SessionProviders from "./session-provider";
import { Noto_Sans_Georgian } from "next/font/google";

// Define the Georgian font
const georgian = Noto_Sans_Georgian({
    subsets: ["latin"],
    style: ["normal"],
    weight: ["100", "900"],
    variable: "--font-georgian",
});

// Define the Geist Sans font
const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body
                className={`${georgian.variable} ${geistSans.variable} antialiased`}
            >
                <SessionProviders>
                    <ReduxProvider>{children}</ReduxProvider>
                </SessionProviders>
            </body>
        </html>
    );
}
