import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className={`h-full ${montserrat.className}`} lang="en">
			<body className="w-screen prose max-w-none bg-gray-50 h-full flex flex-col">
				<div className="w-full bg-white shadow-md"></div>
				<div className="w-full flex-1">
					<div className="container mx-auto h-full">{children}</div>
				</div>
			</body>
		</html>
	);
}
