name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build an application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "MY_GITHUB_ID=${{ secrets.MY_GITHUB_ID }}" >> .env
          echo "MY_GITHUB_SECRET=${{ secrets.MY_GITHUB_SECRET }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Run Build
        run: npm run build
